version: "3.8"
services:
  nginx:
    image: nginx:1.25.1
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./host/dist:/usr/share/nginx/html
      - ./remote1/dist:/var/www/remote1:ro
      - ./remote2/dist:/var/www/remote2:ro
    ports:
      - "80:80"
    depends_on:
      - remote1
      - remote2
      - host

  # host
  host:
    build: ./host
    ports:
      - "3000:3000"
  
  # remote1 MF
  remote1:
    build: ./remote1
    ports:
      - "3001:3001"

  # remote2 MF
  remote2:
    build: ./remote2
    ports:
      - "3002:3002"
